require("codediff").setup {
  diff = {
    layout = "side-by-side",
    disable_inlay_hints = true,
    max_computation_time_ms = 10000,
    ignore_trim_whitespace = false,
    hide_merge_artifacts = true,
    original_position = "left",
    cycle_next_hunk = true,
    cycle_next_file = true,
    jump_to_first_change = true,
    highlight_priority = 120,
    compute_moves = true,
  },
  explorer = {
    position = "left",
    hidden = false,
    width = 36,
    auto_refresh = true,
    indent_markers = true,
    initial_focus = "explorer",
    view_mode = "tree",
    flatten_dirs = true,
    focus_on_select = false,
    file_filter = {
      ignore = { ".git/**", ".jj/**", "node_modules/**", "dist/**", "target/**" },
    },
    visible_groups = {
      staged = true,
      unstaged = true,
      conflicts = true,
    },
  },
  history = {
    position = "bottom",
    height = 16,
    initial_focus = "history",
    view_mode = "tree",
  },
  keymaps = {
    view = {
      quit = "q",
      toggle_explorer = "<leader>b",
      focus_explorer = "<leader>e",
      next_hunk = "]c",
      prev_hunk = "[c",
      next_file = "<tab>",
      prev_file = "<s-tab>",
      diff_get = "do",
      diff_put = "dp",
      open_in_prev_tab = "gf",
      close_on_open_in_prev_tab = false,
      toggle_stage = "-",
      stage_hunk = "<leader>hs",
      unstage_hunk = "<leader>hu",
      discard_hunk = "<leader>hr",
      hunk_textobject = "ih",
      show_help = "?",
      align_move = "gm",
      toggle_layout = "t",
    },
    explorer = {
      select = "<CR>",
      hover = "K",
      refresh = "R",
      toggle_view_mode = "i",
      stage_all = "S",
      unstage_all = "U",
      restore = "X",
      toggle_changes = "gu",
      toggle_staged = "gs",
      fold_open = "zo",
      fold_open_recursive = "zO",
      fold_close = "zc",
      fold_close_recursive = "zC",
      fold_toggle = "za",
      fold_toggle_recursive = "zA",
      fold_open_all = "zR",
      fold_close_all = "zM",
    },
    history = {
      select = "<CR>",
      toggle_view_mode = "i",
      refresh = "R",
      fold_open = "zo",
      fold_open_recursive = "zO",
      fold_close = "zc",
      fold_close_recursive = "zC",
      fold_toggle = "za",
      fold_toggle_recursive = "zA",
      fold_open_all = "zR",
      fold_close_all = "zM",
    },
    conflict = {
      accept_incoming = "\\ct",
      accept_current = "\\co",
      accept_both = "\\cb",
      discard = "\\cx",
      accept_all_incoming = "\\cT",
      accept_all_current = "\\cO",
      accept_all_both = "\\cB",
      discard_all = "\\cX",
      next_conflict = "]x",
      prev_conflict = "[x",
      diffget_incoming = "2do",
      diffget_current = "3do",
    },
  },
}

local code_diff_keymaps = {
  { "n", "<leader>gd", "<cmd>CodeDiff<CR>", "CodeDiff changed files" },
  { "n", "<leader>gD", "<cmd>CodeDiff --inline<CR>", "CodeDiff changed files inline" },
  { "n", "<leader>gf", "<cmd>CodeDiff file HEAD<CR>", "CodeDiff current file vs HEAD" },
  { "n", "<leader>gm", "<cmd>CodeDiff main...<CR>", "CodeDiff PR against main" },
  { "n", "<leader>gh", "<cmd>CodeDiff history --reverse<CR>", "CodeDiff recent history" },
  { "n", "<leader>gH", "<cmd>CodeDiff history % --reverse<CR>", "CodeDiff current file history" },
  { "x", "<leader>gh", ":'<,'>CodeDiff history --reverse<CR>", "CodeDiff selected lines history" },
}

for _, keymap in ipairs(code_diff_keymaps) do
  vim.keymap.set(keymap[1], keymap[2], keymap[3], { desc = keymap[4] })
end
