vim.g.codeium_disable_bindings = 1
vim.keymap.set("i", "<c-y>", function()
  return vim.fn["codeium#Accept"]()
end, { expr = true })
vim.keymap.set("i", "<Down>", function()
  return vim.fn["codeium#CycleCompletions"](1)
end, { expr = true })
vim.keymap.set("i", "<Up>", function()
  return vim.fn["codeium#CycleCompletions"](-1)
end, { expr = true })
vim.keymap.set("i", "<Left>", function()
  return vim.fn["codeium#Clear"]()
end, { expr = true })
